// priority: 3000

// 整合包全局变量
global.creatorList = [
    "c764069d-485d-4907-bbe2-33d3b3d1486c",
    "491969fe-807c-4c93-8574-90febb80d230"
]

global.modList = new Set([
    "enderzoology",
    "supermartijn642configlib",
    "sodium_extra",
    "deathcounter",
    "saeculariacaudices",
    "prefab",
    "enderio_base",
    "hammerlib",
    "projecte",
    "bettercaves",
    "endercore",
    "forgeendertech",
    "ctm",
    "neoforge",
    "modernfix",
    "fabric_block_view_api_v2",
    "krypton_fnp",
    "yungsapi",
    "accessible_step",
    "iris",
    "bagus_lib",
    "biolith",
    "chancecubes",
    "ae2importexportcard",
    "forgivingvoid",
    "clientsort",
    "balm",
    "snowrealmagic",
    "prickle",
    "jeresources",
    "energeticsheep",
    "betterfortresses",
    "cloth_config",
    "sound_physics_remastered",
    "staaaaaaaaaaaack",
    "powerscale",
    "glodium",
    "liblib_core",
    "torchmaster",
    "the_ruler",
    "fabric_game_rule_api_v1",
    "propertymodifier",
    "supermartijn642corelib",
    "botania",
    "resourcefulconfig",
    "spark",
    "reeses_sodium_options",
    "potioncore",
    "curios",
    "ias",
    "searchables",
    "accessories",
    "cumulus_menus",
    "liblib_glitter",
    "globalxp",
    "conditional_mixin",
    "transition",
    "invmove_compat",
    "fabric_rendering_data_attachment_v1",
    "nitrogen_internals",
    "jadeaddons",
    "fastleafdecay",
    "codechickenlib",
    "enderio_machines",
    "bettermineshafts",
    "netherex",
    "liblib_mosaic",
    "ae2jeiintegration",
    "eat_eat_eat",
    "kiwi",
    "effectdescriptions",
    "clienttweaks",
    "puffish_skills",
    "mowziesmobs",
    "jea",
    "rechiseled",
    "customskinloader",
    "bountifulbaubles",
    "fabric_model_loading_api_v1",
    "jei",
    "lithium",
    "attributefix",
    "bibliocraft",
    "passablefoliage",
    "fabric_renderer_indigo",
    "naturescompass",
    "libx",
    "compactmachines",
    "champions",
    "glitchcore",
    "sereneseasons",
    "farmingforblockheads",
    "fusion",
    "sodium",
    "ruins",
    "ironchest",
    "drippyloadingscreen",
    "zerocore",
    "minecraft",
    "scena",
    "terrablender",
    "biomesoplenty",
    "itemphysiclite",
    "fabric_api_base",
    "mousetweaks",
    "magicfeather",
    "pamhc2crops",
    "justenoughbreeding",
    "cubes_without_borders",
    "mekanism_lasers",
    "adlods",
    "kotlinforforge",
    "notenoughanimations",
    "xaerominimap",
    "pamhc2foodcore",
    "gravestone",
    "astages",
    "polymorph",
    "lootbags",
    "zeta",
    "enderio_conduits_modded",
    "appleskin",
    "modernui",
    "puzzleslib",
    "minemenu",
    "liblib_albedo",
    "cyclopscore",
    "kuma_api",
    "fabric_renderer_api_v1",
    "netherportalfix",
    "geckolib",
    "filesjs",
    "new_classic_battle_towers",
    "aether",
    "firstperson",
    "tipsmod",
    "projectexpansion",
    "sophisticatedcore",
    "kleeslabs",
    "xaeromaps_waystones",
    "xaeroworldmap",
    "cookingforblockheads",
    "controlling",
    "placebo",
    "fastfurnace",
    "jumpoverfences",
    "dankstorage",
    "gravestonecurioscompat",
    "bookshelf",
    "sophisticatedbackpacks",
    "waddles",
    "additionalstructures",
    "textformattingeverywhere",
    "sodiumoptionsapi",
    "melody",
    "baguettelib",
    "noincreasingrepaircost",
    "fzzy_config",
    "particle_core",
    "dummmmmmy",
    "twilightforest",
    "sodiumdynamiclights",
    "konkrete",
    "ambientsounds",
    "jearchaeology",
    "projectvibrantjourneys",
    "pamhc2foodextended",
    "solarflux",
    "actuallyadditions",
    "patchouli",
    "collective",
    "randomthings",
    "liblib_etcetera",
    "mysticalcustomization",
    "lostcities",
    "betterstrongholds",
    "kjsutils",
    "deeperdarker",
    "architectury",
    "nerb",
    "ftblibrary",
    "hooked",
    "ftbfiltersystem",
    "findme",
    "ftbteams",
    "ftbquests",
    "ftbranks",
    "ftbessentials",
    "ageingspawners",
    "lanserverproperties",
    "bigreactors",
    "refurbished_furniture",
    "packagedavaritia",
    "framework",
    "probejs",
    "polylib",
    "tofucraft",
    "betteradvancements",
    "tide",
    "rhino",
    "kubejs",
    "owo",
    "cucumber",
    "trashslot",
    "pamhc2trees",
    "librarianlib",
    "mca",
    "snad",
    "redstonepen",
    "octolib",
    "ash_api",
    "commonnetworking",
    "accessories_compat_layer",
    "tclayer",
    "cclayer",
    "hardcoreastagesitem",
    "trender",
    "invmove",
    "waystones",
    "yungscavebiomes",
    "configured",
    "dungeoncrawl",
    "ftbbackups2",
    "bonsaitrees4",
    "mcjtylib",
    "rftoolsbase",
    "xnet",
    "rftoolsdim",
    "rftoolspower",
    "rftoolsbuilder",
    "rftoolsstorage",
    "rftoolscontrol",
    "guideme",
    "toastcontrol",
    "ichunutil",
    "enderstorage",
    "defiled_lands_reborn",
    "akashictome",
    "ftbchunks",
    "ftbxmodcompat",
    "extensibleenums",
    "brandonscore",
    "draconicevolution",
    "mysticalagriculture",
    "mysticalagradditions",
    "saplanting",
    "ambience_mini",
    "rftoolsutility",
    "mekanism_unleashed",
    "mekanism",
    "mekanism_extras",
    "mekmm",
    "kubejs_mekanism",
    "mekanismgenerators",
    "xnetgases",
    "enchdesc",
    "moonlight",
    "enderio_conduits",
    "avaritia",
    "silentlib",
    "jade",
    "ae2",
    "extendedae",
    "rechiseledae2",
    "megacells",
    "ae2addonlib",
    "ae2ct",
    "ae2netanalyser",
    "extendedae_plus",
    "advanced_ae",
    "ae2wtlib_api",
    "creativecore",
    "enderio_armory",
    "packagedauto",
    "difficultylock",
    "uilib",
    "yamlconfig",
    "tinymobfarm",
    "enderio",
    "quark",
    "polyeng",
    "fastbench",
    "storagedrawers",
    "fluiddrawerslegacy",
    "fluxnetworks",
    "jei_mekanism_multiblocks",
    "jecharacters",
    "inventoryhud",
    "buildinggadgets2",
    "cryonicconfig",
    "screenshotclipboard",
    "fancymenu",
    "coroutil",
    "zombieawareness",
    "ferritecore",
    "chisel",
    "yet_another_config_lib_v3",
    "solcarrot",
    "exporbrecall",
    "appmek",
    "packetfixer",
    "chiselsandbits",
    "armor_visibility",
    "openloader",
    "betterfoliage",
    "iconexporter",
    "xmxw",
    "enderio_modded_conduits",
    "xaerolib",
    "pouchofunknownnirvana",
    "summoningrituals"
])

global.commandWhiteList = [
    "neoforge",
    "reload",
    "seed",
    "say",
    "help",
    "list",
    "msg",
    "teammsg",
    "tell",
    "tellraw",
    "title",
    "trigger",
    "backup",
    "tpa",
    "tpaccept",
    "greedycraft",
    "sethome",
    "home"
]

global.commandBlackList = [
    "gamemode",
    "gamerule",
    "give",
    "setblock",
    "fill",
    "execute",
    "summon",
    "xp",
    "tp",
    "kill",
    "effect",
    "advancement",
    "data",
    "tick",
    "damage",
    "fly",
    "mek",
    "astages",
    "ftbquests",
    "kubejs",
    "projecte",
    "projectexpansion"
]

global.stageList = [
    "getting_started",
    "twilight_forest",
    "twilight_shield",
    "nether",
    "gaia_killer",
    "wither_killer",
    "fearless_man",
    "ender_charm",
    "hardmode",
    "fusion_matrix"
]

global.dimensionDifficulty = {
    "minecraft:the_nether": 25,
    "minecraft:the_end": 50,
    "aether:the_aether": 30,
    "deeperdarker:otherside": 65
}

global.mysticalAgricultureSeedLevelMap = {
    "mysticalagriculture:inferium_seeds": 1,
    "mysticalagriculture:stone_seeds": 1,
    "mysticalagriculture:dirt_seeds": 1,
    "mysticalagriculture:wood_seeds": 1,
    "mysticalagriculture:ice_seeds": 1,
    "mysticalagriculture:deepslate_seeds": 1,
    "mysticalagriculture:nature_seeds": 2,
    "mysticalagriculture:dye_seeds": 2,
    "mysticalagriculture:nether_seeds": 2,
    "mysticalagriculture:coal_seeds": 2,
    "mysticalagriculture:coral_seeds": 2,
    "mysticalagriculture:honey_seeds": 2,
    "mysticalagriculture:amethyst_seeds": 2,
    "mysticalagriculture:pig_seeds": 2,
    "mysticalagriculture:chicken_seeds": 2,
    "mysticalagriculture:cow_seeds": 2,
    "mysticalagriculture:sheep_seeds": 2,
    "mysticalagriculture:squid_seeds": 2,
    "mysticalagriculture:fish_seeds": 2,
    "mysticalagriculture:slime_seeds": 2,
    "mysticalagriculture:turtle_seeds": 2,
    "mysticalagriculture:armadillo_seeds": 2,
    "mysticalagriculture:rubber_seeds": 2,
    "mysticalagriculture:silicon_seeds": 2,
    "mysticalagriculture:sulfur_seeds": 2,
    "mysticalagriculture:aluminum_seeds": 2,
    "mysticalagriculture:saltpeter_seeds": 2,
    "mysticalagriculture:apatite_seeds": 2,
    "mysticalagriculture:grains_of_infinity_seeds": 2,
    "mysticalagriculture:mystical_flower_seeds": 2,
    "mysticalagriculture:marble_seeds": 2,
    "mysticalagriculture:limestone_seeds": 2,
    "mysticalagriculture:basalt_seeds": 2,
    "mysticalagriculture:iron_seeds": 3,
    "mysticalagriculture:copper_seeds": 3,
    "mysticalagriculture:nether_quartz_seeds": 3,
    "mysticalagriculture:glowstone_seeds": 3,
    "mysticalagriculture:redstone_seeds": 3,
    "mysticalagriculture:obsidian_seeds": 3,
    "mysticalagriculture:prismarine_seeds": 3,
    "mysticalagriculture:zombie_seeds": 3,
    "mysticalagriculture:skeleton_seeds": 3,
    "mysticalagriculture:creeper_seeds": 3,
    "mysticalagriculture:spider_seeds": 3,
    "mysticalagriculture:phantom_seeds": 3,
    "mysticalagriculture:rabbit_seeds": 3,
    "mysticalagriculture:tin_seeds": 3,
    "mysticalagriculture:bronze_seeds": 3,
    "mysticalagriculture:zinc_seeds": 3,
    "mysticalagriculture:brass_seeds": 3,
    "mysticalagriculture:silver_seeds": 3,
    "mysticalagriculture:lead_seeds": 3,
    "mysticalagriculture:graphite_seeds": 3,
    "mysticalagriculture:copper_alloy_seeds": 3,
    "mysticalagriculture:redstone_alloy_seeds": 3,
    "mysticalagriculture:conductive_alloy_seeds": 3,
    "mysticalagriculture:manasteel_seeds": 3,
    "mysticalagriculture:steeleaf_seeds": 3,
    "mysticalagriculture:ironwood_seeds": 3,
    "mysticalagriculture:sky_stone_seeds": 3,
    "mysticalagriculture:certus_quartz_seeds": 3,
    "mysticalagriculture:gold_seeds": 4,
    "mysticalagriculture:lapis_lazuli_seeds": 4,
    "mysticalagriculture:end_seeds": 4,
    "mysticalagriculture:experience_seeds": 4,
    "mysticalagriculture:breeze_seeds": 4,
    "mysticalagriculture:blaze_seeds": 4,
    "mysticalagriculture:ghast_seeds": 4,
    "mysticalagriculture:enderman_seeds": 4,
    "mysticalagriculture:steel_seeds": 4,
    "mysticalagriculture:nickel_seeds": 4,
    "mysticalagriculture:constantan_seeds": 4,
    "mysticalagriculture:electrum_seeds": 4,
    "mysticalagriculture:invar_seeds": 4,
    "mysticalagriculture:uranium_seeds": 4,
    "mysticalagriculture:ruby_seeds": 4,
    "mysticalagriculture:sapphire_seeds": 4,
    "mysticalagriculture:peridot_seeds": 4,
    "mysticalagriculture:soulium_seeds": 4,
    "mysticalagriculture:soularium_seeds": 4,
    "mysticalagriculture:dark_steel_seeds": 4,
    "mysticalagriculture:pulsating_alloy_seeds": 4,
    "mysticalagriculture:energetic_alloy_seeds": 4,
    "mysticalagriculture:elementium_seeds": 4,
    "mysticalagriculture:osmium_seeds": 4,
    "mysticalagriculture:fluorite_seeds": 4,
    "mysticalagriculture:refined_glowstone_seeds": 4,
    "mysticalagriculture:refined_obsidian_seeds": 4,
    "mysticalagriculture:knightmetal_seeds": 4,
    "mysticalagriculture:fiery_ingot_seeds": 4,
    "mysticalagriculture:fluix_seeds": 4,
    "mysticalagriculture:diamond_seeds": 5,
    "mysticalagriculture:emerald_seeds": 5,
    "mysticalagriculture:netherite_seeds": 5,
    "mysticalagriculture:wither_skeleton_seeds": 5,
    "mysticalagriculture:platinum_seeds": 5,
    "mysticalagriculture:iridium_seeds": 5,
    "mysticalagriculture:vibrant_alloy_seeds": 5,
    "mysticalagriculture:end_steel_seeds": 5,
    "mysticalagriculture:terrasteel_seeds": 5,
    "mysticalagriculture:draconium_seeds": 5,
    "mysticalagriculture:yellorium_seeds": 5,
    "mysticalagriculture:cyanite_seeds": 5,
    "mysticalagriculture:nether_star_seeds": 6,
    "mysticalagriculture:dragon_egg_seeds": 6,
    "mysticalagriculture:gaia_spirit_seeds": 6,
    "mysticalagriculture:awakened_draconium_seeds": 6,
    "mysticalagriculture:neutronium_seeds": 6
}
