// priority: 1000

// 整合包全局变量
global.creatorList = [
    "c764069d-485d-4907-bbe2-33d3b3d1486c",
    "491969fe-807c-4c93-8574-90febb80d230"
]

global.modList = new Set([
    "enderzoology",
    "supermartijn642configlib",
    "deathcounter",
    "saeculariacaudices",
    "prefab",
    "enderio_base",
    "hammerlib",
    "projecte",
    "bettercaves",
    "endercore",
    "forgeendertech",
    "ctm",
    "neoforge",
    "fabric_block_view_api_v2",
    "yungsapi",
    "accessible_step",
    "bagus_lib",
    "biolith",
    "chancecubes",
    "ae2importexportcard",
    "forgivingvoid",
    "clientsort",
    "balm",
    "snowrealmagic",
    "prickle",
    "jeresources",
    "energeticsheep",
    "betterfortresses",
    "cloth_config",
    "sound_physics_remastered",
    "staaaaaaaaaaaack",
    "powerscale",
    "glodium",
    "liblib_core",
    "torchmaster",
    "the_ruler",
    "fabric_game_rule_api_v1",
    "propertymodifier",
    "supermartijn642corelib",
    "botania",
    "resourcefulconfig",
    "spark",
    "potioncore",
    "curios",
    "ias",
    "searchables",
    "accessories",
    "cumulus_menus",
    "liblib_glitter",
    "globalxp",
    "conditional_mixin",
    "transition",
    "invmove_compat",
    "nitrogen_internals",
    "jadeaddons",
    "fastleafdecay",
    "codechickenlib",
    "enderio_machines",
    "bettermineshafts",
    "netherex",
    "liblib_mosaic",
    "ae2jeiintegration",
    "eat_eat_eat",
    "kiwi",
    "effectdescriptions",
    "clienttweaks",
    "puffish_skills",
    "mowziesmobs",
    "jea",
    "rechiseled",
    "customskinloader",
    "bountifulbaubles",
    "fabric_model_loading_api_v1",
    "jei",
    "attributefix",
    "bibliocraft",
    "passablefoliage",
    "fabric_renderer_indigo",
    "naturescompass",
    "libx",
    "compactmachines",
    "champions",
    "glitchcore",
    "sereneseasons",
    "farmingforblockheads",
    "fusion",
    "ruins",
    "ironchest",
    "drippyloadingscreen",
    "zerocore",
    "minecraft",
    "scena",
    "terrablender",
    "biomesoplenty",
    "itemphysiclite",
    "fabric_api_base",
    "mousetweaks",
    "magicfeather",
    "pamhc2crops",
    "justenoughbreeding",
    "cubes_without_borders",
    "mekanism_lasers",
    "adlods",
    "kotlinforforge",
    "notenoughanimations",
    "xaerominimap",
    "pamhc2foodcore",
    "gravestone",
    "astages",
    "polymorph",
    "lootbags",
    "zeta",
    "enderio_conduits_modded",
    "appleskin",
    "modernui",
    "puzzleslib",
    "minemenu",
    "liblib_albedo",
    "cyclopscore",
    "kuma_api",
    "fabric_renderer_api_v1",
    "netherportalfix",
    "geckolib",
    "filesjs",
    "new_classic_battle_towers",
    "aether",
    "firstperson",
    "tipsmod",
    "projectexpansion",
    "sophisticatedcore",
    "kleeslabs",
    "xaeromaps_waystones",
    "xaeroworldmap",
    "cookingforblockheads",
    "controlling",
    "placebo",
    "fastfurnace",
    "jumpoverfences",
    "dankstorage",
    "gravestonecurioscompat",
    "bookshelf",
    "sophisticatedbackpacks",
    "waddles",
    "additionalstructures",
    "textformattingeverywhere",
    "melody",
    "baguettelib",
    "noincreasingrepaircost",
    "fzzy_config",
    "particle_core",
    "dummmmmmy",
    "twilightforest",
    "konkrete",
    "ambientsounds",
    "jearchaeology",
    "projectvibrantjourneys",
    "pamhc2foodextended",
    "solarflux",
    "actuallyadditions",
    "patchouli",
    "collective",
    "randomthings",
    "liblib_etcetera",
    "mysticalcustomization",
    "lostcities",
    "betterstrongholds",
    "kjsutils",
    "architectury",
    "nerb",
    "ftblibrary",
    "hooked",
    "ftbfiltersystem",
    "findme",
    "ftbteams",
    "ftbquests",
    "ftbranks",
    "ftbessentials",
    "ageingspawners",
    "lanserverproperties",
    "bigreactors",
    "refurbished_furniture",
    "packagedavaritia",
    "framework",
    "probejs",
    "polylib",
    "tofucraft",
    "betteradvancements",
    "tide",
    "rhino",
    "kubejs",
    "owo",
    "cucumber",
    "trashslot",
    "pamhc2trees",
    "librarianlib",
    "mca",
    "snad",
    "redstonepen",
    "octolib",
    "ash_api",
    "commonnetworking",
    "accessories_compat_layer",
    "tclayer",
    "cclayer",
    "hardcoreastagesitem",
    "trender",
    "invmove",
    "waystones",
    "yungscavebiomes",
    "configured",
    "dungeoncrawl",
    "ftbbackups2",
    "bonsaitrees4",
    "mcjtylib",
    "rftoolsbase",
    "xnet",
    "rftoolsdim",
    "rftoolspower",
    "rftoolsbuilder",
    "rftoolsstorage",
    "rftoolscontrol",
    "guideme",
    "toastcontrol",
    "ichunutil",
    "enderstorage",
    "defiled_lands_reborn",
    "akashictome",
    "ftbchunks",
    "ftbxmodcompat",
    "extensibleenums",
    "brandonscore",
    "draconicevolution",
    "mysticalagriculture",
    "mysticalagradditions",
    "saplanting",
    "ambience_mini",
    "rftoolsutility",
    "mekanism_unleashed",
    "mekanism",
    "mekanism_extras",
    "mekmm",
    "kubejs_mekanism",
    "mekanismgenerators",
    "xnetgases",
    "enchdesc",
    "moonlight",
    "enderio_conduits",
    "avaritia",
    "silentlib",
    "jade",
    "ae2",
    "extendedae",
    "rechiseledae2",
    "megacells",
    "ae2addonlib",
    "ae2ct",
    "ae2netanalyser",
    "extendedae_plus",
    "advanced_ae",
    "ae2wtlib_api",
    "creativecore",
    "enderio_armory",
    "packagedauto",
    "difficultylock",
    "uilib",
    "yamlconfig",
    "tinymobfarm",
    "enderio",
    "quark",
    "polyeng",
    "fastbench",
    "storagedrawers",
    "fluiddrawerslegacy",
    "fluxnetworks",
    "jei_mekanism_multiblocks",
    "jecharacters",
    "inventoryhud",
    "buildinggadgets2",
    "cryonicconfig",
    "screenshotclipboard",
    "fancymenu",
    "coroutil",
    "zombieawareness",
    "chisel",
    "yet_another_config_lib_v3",
    "solcarrot",
    "exporbrecall",
    "appmek",
    "packetfixer",
    "chiselsandbits",
    "armor_visibility",
    "openloader",
    "betterfoliage"
])

global.commandWhiteList = [
    "neoforge",
    "reload",
    "seed",
    "say",
    "help",
    "list",
    "msg",
    "teammsg",
    "tell",
    "tellraw",
    "title",
    "trigger",
    "backup",
    "tpa",
    "tpaccept",
    "setPackModeToCasual",
    "setPackModeToAdventure",
    "setPackModeToExpert",
    "hidescoreboard",
    "showscoreboard",
    "sethome",
    "home"
]

global.commandBlackList = [
    "gamemode",
    "gamerule",
    "give",
    "setblock",
    "fill",
    "execute",
    "summon",
    "xp",
    "tp",
    "kill",
    "effect",
    "advancement",
    "data",
    "tick",
    "damage",
    "fly",
    "mek",
    "astages",
    "ftbquests",
    "kubejs"
]

global.stages = {
    item: {
        getting_started: [
            '#c:player_workstations/crafting_tables',
            '#minecraft:planks',
            '#c:chests',
            '#c:cobblestones',
            '#c:ingots/iron',
            '#c:ingots/gold',
            '#c:nuggets/iron',
            '#c:nuggets/gold',
            '#c:dusts/iron',
            '#c:dusts/gold',
            'minecraft:wooden_pickaxe',
            'minecraft:stone_pickaxe',
            'minecraft:diamond_pickaxe',
            'minecraft:golden_pickaxe',
            'minecraft:wooden_axe',
            'minecraft:stone_axe',
            'minecraft:diamond_axe',
            'minecraft:golden_axe',
            'minecraft:iron_axe',
            'minecraft:iron_block',
            'minecraft:gold_block',
            'greedycraft:twilight_gem'
        ],
        twilight_forest: [
            'greedycraft:twilight_shield'
        ],
        nether: [
            '#c:dusts/quartz',
            '#c:ores/quartz',
            '#c:blocks/quartz_block',
            '#minecraft:anvil',
            '#greedycraft:material/aeroite',
            '#greedycraft:material/asgardium',
            '#greedycraft:material/aqualite',
            '#greedycraft:material/durasteel',
            '#ae2:all_quartz',
            'ae2:certus_quartz_dust',
            'ae2:fluix_dust',
            'botania:life_essence',
            'botania:gaia_ingot',
            'minecraft:netherite_ingot',
            'minecraft:netherite_block',
            'minecraft:ancient_debris',
            'minecraft:netherite_scrap',
            'minecraft:glowstone',
            'minecraft:glowstone_dust',
            'minecraft:quartz',
            'minecraft:beacon',
            'minecraft:blaze_rod',
            'minecraft:blaze_powder',
            'minecraft:ender_eye',
            'minecraft:enchanted_book',
            'minecraft:enchanting_table',
            'minecraft:brewing_stand',
            'minecraft:ghast_tear',
            'minecraft:magma_cream',
            // 'greedycraft:sponsors_chest',
            // 'greedycraft:shining_star',
            // 'greedycraft:medkit_big',
            // 'greedycraft:blood_sigil',
            // 'greedycraft:bloody_sacrifice',
            // 'greedycraft:awakened_eye',
            // 'greedycraft:sponsor_chest_fragment',
            'defiled_lands_reborn:ravaging_essence',
            'defiled_lands_reborn:ravaging_ingot',
            'defiled_lands_reborn:remorseful_essence',
            'defiled_lands_reborn:remorseful_gem',
            'extendedae:entro_ingot',
            'extendedae:entro_dust',
            'extendedae:entro_block',
            'ae2:formation_core',
            'ae2:annihilation_core',
            'defiled_lands_reborn:idol_sorrow',
            'defiled_lands_reborn:calling_stone',
            'quark:blaze_lantern',
            'enderio:dark_steel_sword',
            'botania:enchanter',
            'hooked:redstone_hook',
            'enderio:withering_powder'
        ],
        gaia_killer: [
            'minecraft:nether_star',
            'minecraft:wither_skeleton_skull'
        ],
        wither_killer: [
            // 'greedycraft:bravery_certificate',
            // 'greedycraft:ender_charm',
            'enderio:reinforced_obsidian_block',
            'enderio:redstone_alloy_ingot',
            'mysticalagriculture:witherproof_block',
            'mysticalagriculture:witherproof_glass',
            'minecraft:end_crystal'
        ],
    },
    ore: {
        getting_started: {
            "#c:player_workstations/crafting_tables": "greedycraft:unknown_block",
            "#c:chests": "greedycraft:unknown_block"
        },
        nether: {
            "#minecraft:anvil": "greedycraft:unknown_block",
            "minecraft:beacon": "greedycraft:unknown_block",
            "minecraft:enchanting_table": "greedycraft:unknown_block",
            "minecraft:nether_quartz_ore": "minecraft:netherrack",
            "netherex:fiery_quartz_ore": "netherex:fiery_netherrack",
            "netherex:gloomy_quartz_ore": "netherex:gloomy_netherrack",
            "netherex:lively_quartz_ore": "netherex:lively_netherrack",
            "greedycraft:aeroite_ore": "aether:cold_aercloud",
            "greedycraft:asgardium_ore": "aether:holystone"
        }
    },
    dimension: {
        twilight_shield: [
            "minecraft:the_nether"
        ],
        nether: [
            "aether:the_aether"
        ],
    },
    mod: {
        nether: [
            "aether"
        ]
    },
    mob: {
        twilight_shield: [
            "minecraft:blaze",
            "minecraft:wither_skeleton"
        ],
        gaia_killer: [
            "minecraft:wither"
        ]
    }
}

global.dimensionDifficulty = {
    "minecraft:the_nether": 25,
    "minecraft:the_end": 50,
    "aether:the_aether": 30
}